# 01. Importing Libraries

In [1]:
import os
import math
import random
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import scipy
import numpy as np
import pandas as pd
import scipy.stats as st

# 02. Importing Data

In [2]:
books = pd.read_csv('../01. Data/books_with_clusters.csv')

# 03. Beautification of Database

In [3]:
books.head()

,book_id,title,author,avg_rating,num_ratings,cover_img_url,goodreads_url,source,year_published,genres,description,pages,series,isbn,publisher,language,ol_key,google_url,cluster,genres_clean
0,0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,4.35,10115839.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/2767052-th...,GoodReads,2008,"Young Adult, Dystopia, Fiction, Fantasy, Scien...",Winning means fame and fortune. Losing means c...,374.0,The Hunger Games#1,NaN,NaN,NaN,NaN,NaN,4,"Young Adult, Dystopia, Fiction, Fantasy, Scien..."
1,1,Pride and Prejudice,Jane Austen,4.30,4920467.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/1885.Pride...,GoodReads,1813,"Classics, Romance, Fiction, Historical Fiction...","Since its immediate success in 1813,Pride and ...",279.0,NaN,NaN,NaN,NaN,NaN,NaN,2,"Classics, Romance, Fiction, Historical Fiction..."
2,2,To Kill a Mockingbird,Harper Lee,4.26,7016855.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/2657.To_Ki...,GoodReads,1960,"Classics, Fiction, Historical Fiction, School,...","""Shoot all the bluejays you want, if you can h...",323.0,To Kill a Mockingbird#1,NaN,NaN,NaN,NaN,NaN,2,"Classics, Fiction, Historical Fiction, Literat..."
3,3,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.50,3868435.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/58613451-h...,GoodReads,2003,"Fantasy, Fiction, Young Adult, Harry Potter, M...",It's official: the evil Lord Voldemort has ret...,896.0,Harry Potter#5,NaN,NaN,NaN,NaN,NaN,4,"Fantasy, Fiction, Young Adult, Fantasy, Childrens"
4,4,The Book Thief,Markus Zusak,4.39,2935583.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/19063.The_...,GoodReads,2005,"Historical Fiction, Fiction, Young Adult, Clas...",Librarian's note: An alternate cover edition c...,592.0,NaN,NaN,NaN,NaN,NaN,NaN,2,"Historical Fiction, Fiction, Young Adult, Clas..."

In [4]:
# retting index to be book_id
books.set_index('book_id', inplace=True)

In [6]:
# changing num_ratings and pages into INT
books['num_ratings'] = books['num_ratings'].astype('Int64')
books['pages'] = books['pages'].astype('Int64')

In [7]:
books.head()

,title,author,avg_rating,num_ratings,cover_img_url,goodreads_url,source,year_published,genres,description,pages,series,isbn,publisher,language,ol_key,google_url,cluster,genres_clean
book_id,,,,,,,,,,,,,,,,,,,
0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,4.35,10115839,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/2767052-th...,GoodReads,2008,"Young Adult, Dystopia, Fiction, Fantasy, Scien...",Winning means fame and fortune. Losing means c...,374,The Hunger Games#1,NaN,NaN,NaN,NaN,NaN,4,"Young Adult, Dystopia, Fiction, Fantasy, Scien..."
1,Pride and Prejudice,Jane Austen,4.30,4920467,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/1885.Pride...,GoodReads,1813,"Classics, Romance, Fiction, Historical Fiction...","Since its immediate success in 1813,Pride and ...",279,NaN,NaN,NaN,NaN,NaN,NaN,2,"Classics, Romance, Fiction, Historical Fiction..."
2,To Kill a Mockingbird,Harper Lee,4.26,7016855,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/2657.To_Ki...,GoodReads,1960,"Classics, Fiction, Historical Fiction, School,...","""Shoot all the bluejays you want, if you can h...",323,To Kill a Mockingbird#1,NaN,NaN,NaN,NaN,NaN,2,"Classics, Fiction, Historical Fiction, Literat..."
3,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.50,3868435,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/58613451-h...,GoodReads,2003,"Fantasy, Fiction, Young Adult, Harry Potter, M...",It's official: the evil Lord Voldemort has ret...,896,Harry Potter#5,NaN,NaN,NaN,NaN,NaN,4,"Fantasy, Fiction, Young Adult, Fantasy, Childrens"
4,The Book Thief,Markus Zusak,4.39,2935583,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/19063.The_...,GoodReads,2005,"Historical Fiction, Fiction, Young Adult, Clas...",Librarian's note: An alternate cover edition c...,592,NaN,NaN,NaN,NaN,NaN,NaN,2,"Historical Fiction, Fiction, Young Adult, Clas..."

In [8]:
books.isnull().sum()

title                0
author               0
avg_rating         755
num_ratings        733
cover_img_url        4
goodreads_url     1000
source               0
year_published       0
genres               0
description          0
pages               24
series            1529
isbn              1008
publisher         1009
language          1004
ol_key            1004
google_url        1017
cluster              0
genres_clean         0
dtype: int64

In [9]:
# stripping " " from title and author columns
books['title'] = books['title'].str.strip().str.strip('"')
books['author'] = books['author'].str.strip().str.strip('"')

In [10]:
# checking if books with " " in the name were stripped correctly
books[books['title'].str.contains('paint', case=False)][['title', 'genres']]

,title,genres
book_id,,
1121,Painted Scars,"Romance, Dark, Contemporary Romance, Adult, Di..."
1784,I Heard You Paint Houses,"Nonfiction, True Crime"

In [11]:
# removing duplicated genres from genres_list
def remove_duplicate_genres(genre_list):
    seen = []
    for genre in genre_list:
        if genre not in seen:
            seen.append(genre)
    return seen

def clean_genres_string(genres_string):
    genre_list = genres_string.split(', ')
    unique_genres = remove_duplicate_genres(genre_list)
    return ', '.join(unique_genres)

books['genres_clean'] = books['genres_clean'].apply(clean_genres_string)

In [12]:
# checking if duplicated genres were removed correctly
books[books['author'].str.contains('Agatha Christie', case=False)][['title', 'genres_clean']]

,title,genres_clean
book_id,,
92,And Then There Were None,"Mystery, Classics, Fiction, Thriller, Crime"
215,"Murder on the Orient Express (Hercule Poirot, ...","Mystery, Classics, Fiction, Crime, Thriller"
801,"The Murder of Roger Ackroyd (Hercule Poirot, #4)","Mystery, Fiction, Classics, Crime, Thriller"
838,"Death on the Nile (Hercule Poirot, #18)","Mystery, Fiction, Classics, Crime, Thriller"
1125,The Mystery of the Blue Train,"Crimes Against, Mystery, Fiction"
1126,Endless Night,"Fiction, Mystery"
1144,Death on the Nile,"Fiction, Mystery"

In [13]:
# allowing me to see all the rows in the dataset
pd.set_option('display.max_rows', None)

In [14]:
books[['title', 'author', 'description', 'series']]

,title,author,description,series
book_id,,,,
0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,Winning means fame and fortune. Losing means c...,The Hunger Games#1
1,Pride and Prejudice,Jane Austen,"Since its immediate success in 1813,Pride and ...",NaN
2,To Kill a Mockingbird,Harper Lee,"""Shoot all the bluejays you want, if you can h...",To Kill a Mockingbird#1
3,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,It's official: the evil Lord Voldemort has ret...,Harry Potter#5
4,The Book Thief,Markus Zusak,Librarian's note: An alternate cover edition c...,NaN
5,"Twilight (Twilight Saga, #1)",Stephenie Meyer,About three things I was absolutely positive.F...,The Twilight Saga#1
6,Animal Farm,George Orwell,Librarian's note: There is an Alternate Cover ...,NaN
7,J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...,J.R.R. Tolkien,These magical adaptations became instant class...,Middle Earth#1-4
8,The Chronicles of Narnia (The Chronicles of Na...,C.S. Lewis,Librarian note:An alternate cover for this edi...,The Chronicles of Narnia (Chronological Order)...
9,The Fault in Our Stars,John Green,Despite the tumor-shrinking medical miracle th...,NaN
10,The Picture of Dorian Gray,Oscar Wilde,"In this celebrated work, his only novel, Wilde...",NaN
11,The Lightning Thief (Percy Jackson and the Oly...,Rick Riordan,Alternate cover for this ISBN can be foundhere...,Percy Jackson and the Olympians#1
12,Wuthering Heights,Emily Brontë,You can find the redesigned cover of this edit...,NaN
13,The Giving Tree,Shel Silverstein,"""Once there was a tree...and she loved a littl...",NaN
14,The Perks of Being a Wallflower,Stephen Chbosky,standing on the fringes of life...offers a uni...,NaN
15,The Little Prince,Antoine de Saint-Exupéry,A pilot forced to land in the Sahara meets a l...,NaN
16,Gone with the Wind,Margaret Mitchell,"Scarlett O'Hara, the beautiful, spoiled daught...",NaN
17,Jane Eyre,Charlotte Brontë,Alternate editions can be foundhereandhere.A g...,NaN
18,The Great Gatsby,F. Scott Fitzgerald,Alternate covers of this ISBN can be foundhere...,NaN
19,Crime and Punishment,Fyodor Dostoevsky,"Raskolnikov, a destitute and desperate former ...",NaN
20,"The Da Vinci Code (Robert Langdon, #2)",Dan Brown,This is an alternate cover for 9780307277671. ...,Robert Langdon#2
21,Alice’s Adventures in Wonderland / Through the...,Lewis Carroll,"""I can't explain myself, I'm afraid, sir,"" sai...",Alice's Adventures in Wonderland#1–2
22,"Divergent (Divergent, #1)",Veronica Roth,She turns to the future in a world that’s fall...,Divergent#1
23,Les Misérables,Victor Hugo,"Victor Hugo's tale of injustice, heroism and l...",NaN
24,"Anne of Green Gables (Anne of Green Gables, #1)",L.M. Montgomery,This heartwarming story has beckoned generatio...,Anne of Green Gables#1
25,Memoirs of a Geisha,Arthur Golden,"A literary sensation and runaway bestseller, t...",NaN
26,The Alchemist,Paulo Coelho,Paulo Coelho's masterpiece tells the mystical ...,NaN
27,Lord of the Flies,William Golding,"At the dawn of the next world war, a plane cra...",NaN
28,Romeo and Juliet,William Shakespeare,"InRomeo and Juliet, Shakespeare creates a viol...",NaN
29,Brave New World,Aldous Huxley,Brave New Worldis a dystopian social science f...,Brave New World#1
30,The Hitchhiker's Guide to the Galaxy (Hitchhik...,Douglas Adams,Seconds before the Earth is demolished to make...,The Hitchhiker’s Guide to the Galaxy#1
31,"City of Bones (The Mortal Instruments, #1)",Cassandra Clare,When fifteen-year-old Clary Fray heads out to ...,The Mortal Instruments#1
32,1984,George Orwell,1984tells us about a world ruled by a totalita...,NaN
33,Dracula,Bram Stoker,You can find an alternative cover edition for ...,NaN
34,The Help,Kathryn Stockett,Three ordinary women are about to take one ext...,NaN
35,Fahrenheit 451,Ray Bradbury,Nearly seventy years after its original public...,Fahrenheit 451
36,Charlotte’s Web,E.B. White,"This beloved book by E. B. White, author ofStu...",NaN
37,Of Mice and Men,John Steinbeck,"“I got you to look after me, and you got me to...",NaN
38,"Ender’s Game (Ender's Saga, #1)",Orson Scott Card,From New York Times bestselling author Orson S...,Ender's Saga#1
39,The Catcher in the Rye,J.D. Salinger,It's Christmas time and Holden Caulfield has j...,NaN
40,"Little Women (Little Women, #1)",Louisa May Alcott,This is an alternate cover edition of ISBN 978...,Little Women#1
41,The Outsiders,S.E. Hinton,The Outsidersis about two weeks in the life of...,NaN
42,One Hundred Years of Solitude,Gabriel García Márquez,Probably Garcí­a Márquez finest and most famou...,NaN
43,A Thousand Splendid Suns,Khaled Hosseini,Mariam is only fifteen when she is sent to Kab...,NaN
44,The Secret Garden,Frances Hodgson Burnett,"In a house full of sadness and secrets, can yo...",NaN
45,The Princess Bride,William Goldman,What happens when the most beautiful girl in t...,NaN
46,"A Game of Thrones (A Song of Ice and Fire, #1)",George R.R. Martin,"Long ago, in a time forgotten, a preternatural...",A Song of Ice and Fire#1
47,The Time Traveler's Wife,Audrey Niffenegger,This is the extraordinary love story of Clare ...,The Time Traveler's Wife#1
48,Harry Potter and the Deathly Hallows (Harry Po...,J.K. Rowling,"It's no longer safe for Harry at Hogwarts, so ...",NaN
49,Frankenstein: The 1818 Text,Mary Wollstonecraft Shelley,Mary Shelley's seminal novel of the scientist ...,NaN
50,The Odyssey,Homer,"Sing to me of the man, Muse, the man of twists...",NaN
51,"The Girl With the Dragon Tattoo (Millennium, #1)",Stieg Larsson,"Harriet Vanger, a scion of one of Sweden’s wea...",Millennium#1
52,"The Handmaid’s Tale (The Handmaid's Tale, #1)",Margaret Atwood,Offred is a Handmaid in the Republic of Gilead...,The Handmaid’s Tale#1
53,"The Giver (Giver, #1)",Lois Lowry,"At the age of twelve, Jonas, a young boy from ...",The Giver#1
54,The Kite Runner,Khaled Hosseini,1970s Twelve-year-old Amir is desperate to win...,NaN
55,"A Wrinkle in Time (Time Quintet, #1)",Madeleine L'Engle,"It was a dark and stormy night; Meg Murry, her...",Time Quintet#1
56,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,"Harry Potter, along with his best friends, Ron...",Harry Potter#3
57,"Dune (Dune, #1)",Frank Patrick Herbert,"Set on the desert planet Arrakis, Dune is the ...",Dune#1
58,Where the Wild Things Are,Maurice Sendak,"Max, a wild and naughty boy, is sent to bed wi...",NaN
59,Green Eggs and Ham,Dr. Seuss,NATIONAL BESTSELLER • Join in the fun with Sam...,NaN
60,The Lovely Bones,Alice Sebold,"""My name was Salmon, like the fish; first name...",NaN
61,The Adventures of Huckleberry Finn (Adventures...,Mark Twain,A nineteenth-century boy from a Mississippi Ri...,Adventures of Tom and Huck#2
62,Life of Pi,Yann Martel,Life of Pi is a fantasy adventure novel by Yan...,NaN
63,Lolita,Vladimir Nabokov,Librarian's note: Alternate cover edition of I...,NaN
64,A Tale of Two Cities,Charles Dickens,A Tale of Two Citiesis Charles Dickens’s great...,NaN
65,Slaughterhouse-Five,Kurt Vonnegut Jr.,"Slaughterhouse-Five, an American classic, is o...",NaN
66,The Bell Jar,Sylvia Plath,The Bell Jar chronicles the crack-up of Esther...,NaN
67,Matilda,Roald Dahl,“The Trunchbull”is no match for Matilda!Matild...,NaN
68,Water for Elephants,Sara Gruen,"When Jacob Jankowski, recently orphaned and su...",NaN
69,Harry Potter and the Philosopher's Stone (Harr...,J.K. Rowling,An alternative cover for this ASIN can be foun...,Harry Potter#1
70,The Stand,Stephen King,This is the way the world ends: with a nanosec...,NaN
71,Catch-22,Joseph Heller,"Fifty years after its original publication, Ca...",Catch-22#1
72,The Adventures of Sherlock Holmes (Sherlock Ho...,Arthur Conan Doyle,The world-famous crime-solving duo Holmes and ...,NaN
73,A Clockwork Orange,Anthony Burgess,In Anthony Burgess's influential nightmare vis...,NaN
74,"The Pillars of the Earth (Kingsbridge, #1)",Ken Follett,Ken Follett is known worldwide as the master o...,Kingsbridge#1
75,Rebecca,Daphne du Maurier,Last night I dreamt I went to Manderley again....,NaN
76,"Watership Down (Watership Down, #1)",Richard Adams,Librarian's note: See alternate cover edition ...,Watership Down#1
77,The Color Purple,Alice Walker,"Read the original inspiration for the new, bol...",The Color Purple Collection#1
78,Great Expectations,Charles Dickens,Great Expectations charts the progress of Pip ...,NaN
79,"Outlander (Outlander, #1)",Diana Gabaldon,"The year is 1945. Claire Randall, a former com...",Outlander#1
80,The Elephant Tree,R.D. Ronald,Mark Fallon is an overworked detective investi...,NaN
81,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. Tolkien,"Sauron, the Dark Lord, has gathered to him all...",Middle Earth#2
82,Anna Karenina,Leo Tolstoy,Acclaimed by many as the world's greatest nove...,NaN
83,One Flew Over the Cuckoo’s Nest,Ken Kesey,Alternate cover edition of ISBN9780451163967Ty...,NaN
84,The Brothers Karamazov,Fyodor Dostoevsky,"The Brothers Karamazov is a murder mystery, a ...",NaN
85,My Sister's Keeper,Jodi Picoult,New York Timesbest-selling author Jodi Picoult...,NaN
86,The Zombie Room,R.D. Ronald,An unlikely bond is forged between three men f...,NaN
87,A Tree Grows in Brooklyn,Betty Smith,The beloved American classic about a young gir...,NaN
88,The Road,Cormac McCarthy,"A searing, postapocalyptic novel destined to b...",NaN
89,Harry Potter and the Goblet of Fire (Harry Pot...,J.K. Rowling,"Lord Voldemort, the dark wizard responsible fo...",Harry Potter#4
90,Gone Girl,Gillian Flynn,Who are you? What have we done to each other? ...,NaN
91,"The Golden Compass (His Dark Materials, #1)",Philip Pullman,"Lyra is rushing to the cold, far North, where ...",His Dark Materials#1
92,And Then There Were None,Agatha Christie,"First, there were ten—a curious assortment of ...",NaN
93,Siddhartha,Hermann Hesse,"Herman Hesse's classic novel has delighted, in...",NaN
94,"Vampire Academy (Vampire Academy, #1)",Richelle Mead,Only a true best friend can protect you from y...,Vampire Academy#1
95,Don Quixote,Miguel de Cervantes Saavedra,Don Quixote has become so entranced by reading...,Don Quijote de la Mancha#1-2
96,"Angela's Ashes (Frank McCourt, #1)",Frank McCourt,Imbued on every page with Frank McCourt's asto...,Frank McCourt#1
97,The Old Man and the Sea,Ernest Hemingway,Librarian's note: An alternate cover edition c...,NaN
98,The Stranger,Albert Camus,Published in 1942 by French author Albert Camu...,NaN
99,The Poisonwood Bible,Barbara Kingsolver,The Poisonwood Bibleis a story told by the wif...,NaN
100,The Complete Stories and Poems,Edgar Allan Poe,Edgar Allan Poe was one of the most original w...,NaN
101,Dark Places,Gillian Flynn,Libby Day was just seven years old when her ol...,NaN
102,Shutter Island,Dennis Lehane,The year is 1954. U.S. Marshal Teddy Daniels a...,NaN
103,Interview with the Vampire (The Vampire Chroni...,Anne Rice,In a darkened room a young man sits telling th...,The Vampire Chronicles#1
104,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,The war against Voldemort is not going well: e...,Harry Potter#6
105,Atlas Shrugged,Ayn Rand,This is the story of a man who said that he wo...,NaN
106,The Girl Who Played with Fire (Millennium #2),Stieg Larsson,The ExposeMillenium publisher Mikael Blomkvist...,Millennium#2
107,"Winnie-the-Pooh (Winnie-the-Pooh, #1)",A.A. Milne,The adventures of Christopher Robin and his fr...,Winnie-the-Pooh#1
108,"The Notebook (The Notebook, #1)",Nicholas Sparks,Set amid the austere beauty of the North Carol...,The Notebook#1
109,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling,"""Turning the envelope over, his hand trembling...",Harry Potter#1
110,A Story of Yesterday,Sergio Cobo,A Story of Yesterday is a concise and straight...,NaN
111,Perfume: The Story of a Murderer,Patrick Süskind,An alternative cover edition for this ISBN can...,NaN
112,Fight Club,Chuck Palahniuk,Chuck Palahniuk showed himself to be his gener...,Fight Club#1
113,"The Shining (The Shining, #1)",Stephen King,Danny is only five years old but in the words ...,The Shining#1
114,The Secret History,Donna Tartt,Truly deserving of the accolade modern classic...,NaN
115,"Moby-Dick or, The Whale",Herman Melville,"""It is the horrible texture of a fabric that s...",NaN
116,A Prayer for Owen Meany,John Irving,"Eleven-year-old Owen Meany, playing in a Littl...",NaN
117,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,Ever since Harry Potter had come home for the ...,Harry Potter#2
118,"Clockwork Angel (The Infernal Devices, #1)",Cassandra Clare,In a time when Shadowhunters are barely winnin...,The Infernal Devices#1
119,"The Hobbit, or There and Back Again",J.R.R. Tolkien,In a hole in the ground there lived a hobbit. ...,Middle Earth#1
120,The Metamorphosis,Franz Kafka,Alternate cover edition of ISBN 0553213695 / 9...,NaN
121,It,Stephen King,"Welcome to Derry, Maine ...It’s a small city, ...",NaN
122,The Girl on the Train,Paula Hawkins,Rachel catches the same commuter train every m...,NaN
123,The Secret Life of Bees,Sue Monk Kidd,"Set in South Carolina in 1964,The Secret Life ...",NaN
124,The Name of the Wind (The Kingkiller Chronicle...,Patrick Rothfuss,"Told in Kvothe's own voice, this is the tale o...",The Kingkiller Chronicle#1
125,The Red Tent,Anita Diamant,"Her name is Dinah. In the Bible, her life is o...",NaN
126,Mystic River,Dennis Lehane,"When they were children, Sean Devine, Jimmy Ma...",NaN
127,"Red Dragon (Hannibal Lecter, #1)",Thomas Harris,A second family has been massacred by the terr...,Hannibal Lecter#1
128,The Master and Margarita,Mikhail Bulgakov,"The first complete, annotated English Translat...",NaN
129,Never Lie,Freida McFadden,Newlyweds Tricia and Ethan are searching for t...,NaN
130,The Count of Monte Cristo,Alexandre Dumas,An alternative cover edition for this ISBN can...,Le Comte de Monte-Cristo / The Count of Monte ...
131,None of This Is True,Lisa Jewell,Celebrating her forty-fifth birthday at her lo...,NaN
132,Before I Go to Sleep,S.J. Watson,Memories define us.So what if you lost yours e...,NaN
133,"Big Little Lies (Big Little Lies, #1)",Liane Moriarty,An alternative cover edition for this ISBN can...,Big Little Lies#1
134,The Paris Apartment,Lucy Foley,From theNew York Timesbestselling author ofThe...,NaN
135,"The Family Upstairs (The Family Upstairs, #1)",Lisa Jewell,An alternative cover edition for this ISBN can...,The Family Upstairs#1
136,"The Housemaid's Secret (The Housemaid, #2)",Freida McFadden,As he continues showing me their incredible pe...,The Housemaid#2
137,"You (You, #1)",Caroline Kepnes,"When a beautiful, aspiring writer strides into...",You#1
138,Lock Every Door,Riley Sager,No visitors. No nights spent away from the apa...,NaN
139,The Woman in the Window,A.J. Finn,"Anna Fox lives alone, a recluse in her New Yor...",NaN
140,The Last Olympian (Percy Jackson and the Olymp...,Rick Riordan,All year the half-bloods have been preparing f...,Percy Jackson and the Olympians#5
141,"The Woman in Cabin 10 (Lo Blacklock, #1)",Ruth Ware,"Lo Blacklock, a journalist who writes for a tr...",Lo Blacklock#1
142,Pretty Girls,Karin Slaughter,"Twenty years ago Claire Scott's eldest sister,...",NaN
143,Eragon (The Inheritance Cycle #1),Christopher Paolini,An alternate cover edition for ISBN 9780375826...,The Inheritance Cycle#1
144,The Very Hungry Caterpillar,Eric Carle,"THE all-time classic story, from generation to...",Eric Carle's Very Series
145,Home Before Dark,Riley Sager,What was it like? Living in that house.Maggie ...,NaN
146,"The Bone Collector (Lincoln Rhyme, #1)",Jeffery Deaver,Lincoln Rhyme was once a brilliant criminologi...,Lincoln Rhyme#1
147,The Only One Left,Riley Sager,"At seventeen, Lenora HopeHung her sister with ...",NaN
148,The Couple Next Door,Shari Lapena,You never know what's happening on the other s...,NaN
149,Behind Closed Doors,B.A. Paris,THE INSTANT NEW YORK TIMES AND USA TODAY BESTS...,NaN
150,Final Girls,Riley Sager,"Ten years ago, college student Quincy Carpente...",NaN
151,No Exit,Taylor Adams,A kidnapped little girl locked in a stranger's...,NaN
152,"The Last Thing He Told Me (Hannah Hall, #1)",Laura Dave,"Before Owen Michaels disappears, he smuggles a...",NaN
153,"The Lion, the Witch and the Wardrobe (Chronicl...",C.S. Lewis,"Narnia… the land beyond the wardrobe door, a s...",The Chronicles of Narnia#1
154,Looking for Alaska,John Green,Before.Miles “Pudge” Halter is done with his s...,NaN
155,"Six of Crows (Six of Crows, #1)",Leigh Bardugo,Alternate cover of ISBN 9781627792127Ketterdam...,Six of Crows#1
156,Then She Was Gone,Lisa Jewell,"THENShe was fifteen, her mother's golden girl....",NaN
157,A Flicker in the Dark,Stacy Willingham,"When Chloe Davis was twelve, six teenage girls...",NaN
158,Charlie and the Chocolate Factory (Charlie Buc...,Roald Dahl,Charlie Bucket's wonderful adventure begins wh...,Charlie Bucket#1
159,The Adventures of Tom Sawyer,Mark Twain,"The exploits of Tom Sawyer, a consummate prank...",Adventures of Tom and Huck#1
160,Middlesex,Jeffrey Eugenides,The astonishing tale of a gene that passes dow...,NaN
161,The Shadow of the Wind (The Cemetery of Forgot...,Carlos Ruiz Zafón,"Barcelona, 1945: A city slowly heals from its ...",El cementerio de los libros olvidados#1
162,"Tuesdays with Morrie: An Old Man, a Young Man,...",Mitch Albom,"Maybe it was a grandparent, or a teacher or a ...",NaN
163,The Curious Incident of the Dog in the Night-Time,Mark Haddon,Christopher John Francis Boone knows all the c...,NaN
164,"Holes (Holes, #1)",Louis Sachar,Stanley Yelnats is under a curse. A curse that...,Holes#1
165,The Unbearable Lightness of Being,Milan Kundera,"InThe Unbearable Lightness of Being, Milan Kun...",NaN
166,The Name of the Rose,Umberto Eco,The year is 1327. Franciscans in a wealthy Ita...,NaN
167,"Catching Fire (The Hunger Games, #2)",Suzanne Collins,Sparks are igniting.Flames are spreading.And t...,The Hunger Games#2
168,On the Road,Jack Kerouac,A quintessential novel of America & the Beat G...,NaN
169,Where the Red Fern Grows,Wilson Rawls,"Billy, Old Dan, and Little Ann—a boy and his t...",NaN
170,The Song of Achilles,Madeline Miller,Alternate cover edition ofISBN 9780062060624.A...,NaN
171,"The Godfather (The Godfather, #1)",Mario Puzo,The Godfather—the epic tale of crime and betra...,The Godfather#1
172,In Cold Blood,Truman Capote,"On November 15, 1959, in the small town of Hol...",NaN
173,The Scarlet Letter,Nathaniel Hawthorne,The red letter A on her dress marks young moth...,NaN
174,Watchmen,Alan Moore,"Watchmen, the groundbreaking series from award...",Watchmen#1-12
175,American Gods: Tenth Anniversary (American God...,Neil Gaiman,"Days before his release from prison, Shadow's ...",American Gods#1
176,The Divine Comedy: Inferno - Purgatorio - Para...,Dante Alighieri,This Everyman’s Library edition–containing in ...,La Divina Commedia#1-3
177,The Five People You Meet in Heaven,Mitch Albom,From the author of the phenomenal #1 New York ...,The Five People You Meet in Heaven#1
178,All Quiet on the Western Front,Erich Maria Remarque,One by one the boys begin to fall…In 1914 a ro...,All Quiet on the Western Front/The Road Back#1
179,"The Cat in the Hat (Cat in the Hat, #1)",Dr. Seuss,Have a ball with Dr. Seuss and the Cat in the ...,The Cat in the Hat#1
180,American Psycho,Bret Easton Ellis,Patrick Bateman is twenty-six and works on Wal...,NaN
181,Good Omens: The Nice and Accurate Prophecies o...,Terry Pratchett,According to the Nice and Accurate Prophecies ...,NaN
182,"Lonesome Dove (Lonesome Dove, #1)",Larry McMurtry,"A love story, an adventure, and an epic of the...",Lonesome Dove#1
183,"The Little House Collection (Little House, #1-9)",Laura Ingalls Wilder,This nine-book paperback box set of the classi...,Little House#1-9
184,"Hush, Hush (Hush, Hush, #1)",Becca Fitzpatrick,A SACRED OATHA FALLEN ANGELA FORBIDDEN LOVERom...,"Hush, Hush#1"
185,"Peter Pan (Peter Pan, #2)",J.M. Barrie,A fabulously redesigned edition of a Michael H...,Peter Pan#2

In [20]:
# correcting the series column for book_id 334
books.loc[334, ['title', 'author', 'description', 'series']]

title                                 The Wind-Up Bird Chronicle
author                                           Haruki Murakami
description    Japan's most highly regarded novelist now vaul...
series                                            ねじまき鳥クロニクル#1-3
Name: 334, dtype: str

In [21]:
# changing the series
books.loc[334, 'series'] = "The Wind-Up Bird Chronicle #1-3"

In [22]:
books.loc[334, ['title', 'author', 'description', 'series']]

title                                 The Wind-Up Bird Chronicle
author                                           Haruki Murakami
description    Japan's most highly regarded novelist now vaul...
series                           The Wind-Up Bird Chronicle #1-3
Name: 334, dtype: str

In [23]:
# starndardizing the series column
books['series'] = books['series'].str.replace(r'(\S)#', r'\1 #', regex=True)

In [ ]:
books.loc[642, ['title', 'author']]

title                                                    My Ántonia
year_published                                                 1918
description       My Ántonia is a novel published in 1918 by Ame...
Name: 517, dtype: str

In [28]:
# checking the authors to be able to know what to correct in the author column
books.loc[[642, 634, 500, 476, 1462, 1649, 1650, 1677, 1681], ['title', 'author']]

,title,author
book_id,,
642,العصبي,أحمد جمال الدين رمضان
634,انتحار فاشل,أحمد جمال الدين رمضان
500,زندگی مه آلود پریا,سید مرتضی مصطفوی
476,القرآن الكريم,الله
1462,Before the Coffee Gets Cold,川口俊和
1649,Chto takoe iskusstvo? / What is art?,Лев Толстой
1650,Great Dialogues of Plato,Πλάτων
1677,Death's End (The Three-Body Problem Series Boo...,刘慈欣
1681,The Dark Forest (The Three-Body Problem Series...,刘慈欣

In [31]:
# correcting the autor column for roman caracters
author_corrections = {
    'أحمد جمال الدين رمضان': 'Ahmed Gamal El-Din Ramadan',
    'سید مرتضی مصطفوی': 'Seyyed Morteza Mostafavi',
    'الله': 'Anonymous',
    '川口俊和': 'Toshikazu Kawaguchi',
    'Лев Толстой': 'Leo Tolstoy',
    'Πλάττων': 'Plato',
    '刘慈欣': 'Liu Cixin',
    'Πλάτων': 'Plato'
}

books['author'] = books['author'].replace(author_corrections)

In [32]:
# checking if the corrections were made correctly
books.loc[[642, 634, 500, 476, 1462, 1649, 1650, 1677, 1681], ['title', 'author']]

,title,author
book_id,,
642,العصبي,Ahmed Gamal El-Din Ramadan
634,انتحار فاشل,Ahmed Gamal El-Din Ramadan
500,زندگی مه آلود پریا,Seyyed Morteza Mostafavi
476,القرآن الكريم,Anonymous
1462,Before the Coffee Gets Cold,Toshikazu Kawaguchi
1649,Chto takoe iskusstvo? / What is art?,Leo Tolstoy
1650,Great Dialogues of Plato,Plato
1677,Death's End (The Three-Body Problem Series Boo...,Liu Cixin
1681,The Dark Forest (The Three-Body Problem Series...,Liu Cixin

In [35]:
pd.set_option('display.max_colwidth', None)

In [36]:
# checking the title to be able to know what to correct in the title column
books.loc[[7, 274, 307, 384, 461, 476, 500, 634, 642, 1058, 1120, 1125, 1234, 1333, 1508, 1635], ['title', 'author']]

,title,author
book_id,,
7,J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings,J.R.R. Tolkien
274,"[No Country for Old Men] (By: Cormac McCarthy) [published: December, 2007]",Cormac McCarthy
307,"The Lord of the Rings (The Lord of the Rings, #1-3)",J.R.R. Tolkien
384,Midnight Sun [2008 Draft],Stephenie Meyer
461,’Salem’s Lot,Stephen King
476,القرآن الكريم,Anonymous
500,زندگی مه آلود پریا,Seyyed Morteza Mostafavi
634,انتحار فاشل,Ahmed Gamal El-Din Ramadan
642,العصبي,Ahmed Gamal El-Din Ramadan
1058,"A child called ""it",David J. Pelzer
1120,All She Wanted,"Aphrodite Jones, Ariel Jennifer Jones"
1125,The Mystery of the Blue Train,Agatha Christie
1234,Die Aufzeichnungen des Malte Laurids Brigge,Rainer Maria Rilke
1333,... Trotzdem Ja zum Leben sagen,Viktor E. Frankl
1508,Mein Kampf,Adolf Hitler
1635,Sein und Zeit,Martin Heidegger

In [37]:
# correcting title columns for roman caracters and other corrections
title_corrections = {
    'J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings': 'The Hobbit and The Lord of the Rings',
    '[No Country for Old Men] (By: Cormac McCarthy) [published: December, 2007]': 'No Country for Old Men',
    'Midnight Sun [2008 Draft]': 'Midnight Sun',
    "'Salem's Lot": "Salem's Lot",
    'القرآن الكريم': 'The Holy Quran',
    'زندگی مه آلود پریا': 'Misty Life of Pariya',
    'انتحار فاشل': 'Failed Suicide',
    'العصبي': 'The Nervous One',
    'A child called "it': 'A Child Called It',
    'Die Aufzeichnungen des Malte Laurids Brigge': 'The Notebooks of Malte Laurids Brigge',
    '... Trotzdem Ja zum Leben sagen': "Man's Search for Meaning",
    'Sein und Zeit': 'Being and Time',
}

books['title'] = books['title'].replace(title_corrections)

In [38]:
# checking if the corrections were done
books.loc[[7, 274, 307, 384, 461, 476, 500, 634, 642, 1058, 1120, 1125, 1234, 1333, 1508, 1635], ['title', 'author']]

,title,author
book_id,,
7,The Hobbit and The Lord of the Rings,J.R.R. Tolkien
274,No Country for Old Men,Cormac McCarthy
307,"The Lord of the Rings (The Lord of the Rings, #1-3)",J.R.R. Tolkien
384,Midnight Sun,Stephenie Meyer
461,’Salem’s Lot,Stephen King
476,The Holy Quran,Anonymous
500,Misty Life of Pariya,Seyyed Morteza Mostafavi
634,Failed Suicide,Ahmed Gamal El-Din Ramadan
642,The Nervous One,Ahmed Gamal El-Din Ramadan
1058,A Child Called It,David J. Pelzer
1120,All She Wanted,"Aphrodite Jones, Ariel Jennifer Jones"
1125,The Mystery of the Blue Train,Agatha Christie
1234,The Notebooks of Malte Laurids Brigge,Rainer Maria Rilke
1333,Man's Search for Meaning,Viktor E. Frankl
1508,Mein Kampf,Adolf Hitler
1635,Being and Time,Martin Heidegger

In [39]:
# titeling the title and author columns
books['title'] = books['title'].str.title()
books['author'] = books['author'].str.title()

In [ ]:
pd.reset_option('display.max_rows')

# 04. Exporting beautiful dataframe

In [ ]:
# books.to_csv('../01. Data/books_streamlit.csv', index=True)